# Data Exploration: Drill CSV Files

## Setup and Dependencies

In [1]:
# Check if required packages are installed
import importlib.util

packages_to_check = ['pandas']
missing_packages = []

for package in packages_to_check:
    if importlib.util.find_spec(package) is None:
        missing_packages.append(package)

if missing_packages:
    print(f"⚠️  Missing packages: {', '.join(missing_packages)}")
    print(f"Install with: pip install {' '.join(missing_packages)}")
else:
    print("✓ All required packages are installed")

✓ All required packages are installed

In [2]:
# Import required libraries
import pandas as pd
from pathlib import Path

# Define paths
DATA_PATH = Path.home() / "Downloads"

# Define CSV file paths
csv_files = {
    'warmup': DATA_PATH / "warmup_drills.csv",
    'cool_down': DATA_PATH / "cool_down_drills.csv",
    'conditioning_with_ball': DATA_PATH / "conditioning_with_ball.csv",
    'small_sided_games': DATA_PATH / "small_sided_games.csv",
    'tactical': DATA_PATH / "tactical_drills.csv",
    'technical': DATA_PATH / "technical_drills.csv"
}

# Verify all files exist
missing_files = [name for name, path in csv_files.items() if not path.exists()]

if missing_files:
    raise FileNotFoundError(
        f"❌ Missing CSV file(s): {', '.join(missing_files)}\n"
        f"Please ensure all drill CSV files are in your Downloads folder."
    )

print(f"✓ Found all {len(csv_files)} CSV files in {DATA_PATH}")

✓ Found all 6 CSV files in C:\Users\ljega\Downloads

## Preview Each CSV File

In [3]:
# Load and preview each CSV file
for category, file_path in csv_files.items():
    print(f"\n{'='*70}")
    print(f"📁 {category.upper().replace('_', ' ')}")
    print(f"{'='*70}")
    
    # Read the CSV
    df = pd.read_csv(file_path)
    
    # Display basic info
    print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")
    print(f"\nColumns: {df.columns.tolist()}")
    print(f"\nFirst 5 rows:")
    display(df.head())
    print("\n")

======================================================================
📁 WARMUP
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,WU_001,Dynamic Ball Mastery,Warmup,20x20,8,20,ALL,first_touch,cones balls,basic,Light dynamic movements with ball touches betw...
1,WU_002,Tag + Turns,Warmup,15x15,6,16,ALL,agility first_touch,cones,basic,Players move freely and perform quick turns wh...
2,WU_003,Two-Cone Rondo Warmup,Warmup,10x10,5,8,ALL,passing decision_making,cones balls,basic,Simple rondo to get touches and warm up moveme...
3,WU_004,Mirror Movements,Warmup,10x20,4,12,ALL,agility awareness,cones,basic,Partners mirror each other’s movements with ba...
4,WU_005,Juggling Ladder,Warmup,20x20,6,20,ALL,first_touch coordination,balls,intro,Players progress juggling challenges while mov...

======================================================================
📁 COOL DOWN
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,CD_001,Light Passing Pairs,CoolDown,15x15,6,20,ALL,passing,balls,intro,Simple passing while walking and stretching ou...
1,CD_002,Static Stretching Circle,CoolDown,10x10,6,20,ALL,mobility,NaN,intro,Hold each stretch for 20–30 seconds in team ci...
2,CD_003,Breathwork + Touches,CoolDown,10x15,6,20,ALL,first_touch recovery,balls,intro,Slow juggling or touches paired with controlle...
3,CD_004,Partner Resistance Stretch,CoolDown,10x10,4,20,ALL,mobility,NaN,intro,Partners help each other stretch hamstrings an...
4,CD_005,Walking Technical Reset,CoolDown,20x20,8,20,ALL,control,balls,intro,Players walk laps touching the ball every step...

======================================================================
📁 CONDITIONING WITH BALL
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,COND_001,High-Tempo Passing Grid,Conditioning,20x20,6,10,ALL,passing endurance,cones balls,intermediate,Short sharp passing in tight space with consta...
1,COND_002,Dribble Intervals,Conditioning,20x30,6,14,ALL,dribbling stamina,cones balls,beginner,"30 seconds dribble, 15 seconds recovery."
2,COND_003,Sprint-to-Finish Reps,Conditioning,25x20,4,10,"FWD,MID",finishing speed,balls cones,intermediate,Sprint from cone to finish first-time on service.
3,COND_004,Defensive Recovery Runs,Conditioning,30x20,6,12,"DEF,GK",defending pace,cones balls,advanced,Recover from central line into defending shape...
4,COND_005,1v1 Continuous Channel,Conditioning,15x20,4,8,ALL,pace dribbling,cones balls,intermediate,Continuous 1v1 in narrow lane creates repeated...

======================================================================
📁 SMALL SIDED GAMES
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,SSG_001,4v4 + 2 Neutrals,SSG,30x25,10,12,ALL,possession passing,cones bibs balls,intermediate,Neutrals help maintain possession and find cen...
1,SSG_002,3-Goal Game,SSG,30x30,8,12,ALL,decision_making finishing,cones goals balls,intermediate,Teams score on any of three small goals to pro...
2,SSG_003,End Zone Game,SSG,35x25,8,12,ALL,passing movement,cones balls,beginner,Score by receiving in opponent’s end zone.
3,SSG_004,Conditioned Play: Two-Touch,SSG,40x30,10,14,ALL,first_touch speed,cones bibs balls,intermediate,Forces quick decisions and body positioning.
4,SSG_005,Counterattack SSG,SSG,36x28,8,12,"FWD,MID",transition finishing,cones balls,advanced,Immediate counterattacking moments after each ...

======================================================================
📁 TACTICAL
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,TAC_001,Creating Overloads,Tactical,30x40,8,14,"MID,FWD",decision_making possession,cones bibs balls,intermediate,Work on numerical superiority and exploiting o...
1,TAC_002,Building From Back,Tactical,40x50,8,14,"DEF,GK,MID",passing structure,cones bibs balls,advanced,"Shape, movement, and timing to exit pressure a..."
2,TAC_003,Pressing Triggers,Tactical,30x30,6,12,ALL,pressing awareness,cones bibs balls,advanced,Identify cues for team press and coordinate fi...
3,TAC_004,Transition Moments,Tactical,30x40,6,12,ALL,decision_making pace,cones balls,intermediate,Switch instantly between defense and attack af...
4,TAC_005,Wide Channel Decision Play,Tactical,20x40,6,12,"MID,FWD",passing crossing,cones balls,intermediate,Develop patterns down the flanks and final-thi...

======================================================================
📁 TECHNICAL
======================================================================

Shape: 5 rows × 11 columns

Columns: ['drill_id', 'drill_name', 'category', 'field_size_yds', 'players_min', 'players_max', 'positions', 'attributes', 'equipment', 'difficulty', 'description']

First 5 rows:

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description
0,TECH_001,Wall Pass Circuit,Technical,20x30,6,12,"MID,FWD",passing first_touch,cones balls,intermediate,Players rotate through passing checkpoints foc...
1,TECH_002,First Touch Direction,Technical,15x25,4,10,"MID,FWD,DEF",first_touch decision_making,cones balls,intermediate,Receive across body and play into target quickly.
2,TECH_003,1v1 Isolation,Technical,12x18,2,6,"FWD,MID",dribbling finishing,cones balls,intermediate,Quick 1v1 reps with immediate resets.
3,TECH_004,Defensive Jockeying,Technical,10x15,2,8,DEF,defending footwork,cones,intro,Players learn to angle attacker away and time ...
4,TECH_005,Finishing From Angles,Technical,20x30,3,8,FWD,shooting first_touch,balls goals,advanced,Serve from wide areas and finish from staggere...

## Combine All CSV Files

In [10]:
# Combine all CSV files into a single DataFrame with category labels
all_drills = []

for category, file_path in csv_files.items():
    df = pd.read_csv(file_path)
    df['category'] = category
    all_drills.append(df)

# Concatenate all dataframes
drills_raw = pd.concat(all_drills, ignore_index=True)

# Assign duration to each drill based on category
duration_map = {
    'warmup': 15,
    'cool_down': 15,
    'conditioning_with_ball': 15,
    'small_sided_games': 25,
    'tactical': 20,
    'technical': 25
}

drills_raw['duration'] = drills_raw['category'].map(duration_map)

print(f"✓ Combined dataset: {len(drills_raw)} total drills from {len(csv_files)} categories")
print(f"\nDrills by category:")
print(drills_raw['category'].value_counts())
print(f"\nCombined shape: {drills_raw.shape[0]} rows × {drills_raw.shape[1]} columns")
print(f"\nDuration by category:")
print(drills_raw.groupby('category')['duration'].first())

# Preview combined dataset
drills_raw

✓ Combined dataset: 30 total drills from 6 categories

Drills by category:
category
warmup                    5
cool_down                 5
conditioning_with_ball    5
small_sided_games         5
tactical                  5
technical                 5
Name: count, dtype: int64

Combined shape: 30 rows × 12 columns

Duration by category:
category
conditioning_with_ball    15
cool_down                 15
small_sided_games         25
tactical                  20
technical                 25
warmup                    15
Name: duration, dtype: int64

,drill_id,drill_name,category,field_size_yds,players_min,players_max,positions,attributes,equipment,difficulty,description,duration
0,WU_001,Dynamic Ball Mastery,warmup,20x20,8,20,ALL,first_touch,cones balls,basic,Light dynamic movements with ball touches betw...,15
1,WU_002,Tag + Turns,warmup,15x15,6,16,ALL,agility first_touch,cones,basic,Players move freely and perform quick turns wh...,15
2,WU_003,Two-Cone Rondo Warmup,warmup,10x10,5,8,ALL,passing decision_making,cones balls,basic,Simple rondo to get touches and warm up moveme...,15
3,WU_004,Mirror Movements,warmup,10x20,4,12,ALL,agility awareness,cones,basic,Partners mirror each other’s movements with ba...,15
4,WU_005,Juggling Ladder,warmup,20x20,6,20,ALL,first_touch coordination,balls,intro,Players progress juggling challenges while mov...,15
5,CD_001,Light Passing Pairs,cool_down,15x15,6,20,ALL,passing,balls,intro,Simple passing while walking and stretching ou...,15
6,CD_002,Static Stretching Circle,cool_down,10x10,6,20,ALL,mobility,NaN,intro,Hold each stretch for 20–30 seconds in team ci...,15
7,CD_003,Breathwork + Touches,cool_down,10x15,6,20,ALL,first_touch recovery,balls,intro,Slow juggling or touches paired with controlle...,15
8,CD_004,Partner Resistance Stretch,cool_down,10x10,4,20,ALL,mobility,NaN,intro,Partners help each other stretch hamstrings an...,15
9,CD_005,Walking Technical Reset,cool_down,20x20,8,20,ALL,control,balls,intro,Players walk laps touching the ball every step...,15
10,COND_001,High-Tempo Passing Grid,conditioning_with_ball,20x20,6,10,ALL,passing endurance,cones balls,intermediate,Short sharp passing in tight space with consta...,15
11,COND_002,Dribble Intervals,conditioning_with_ball,20x30,6,14,ALL,dribbling stamina,cones balls,beginner,"30 seconds dribble, 15 seconds recovery.",15
12,COND_003,Sprint-to-Finish Reps,conditioning_with_ball,25x20,4,10,"FWD,MID",finishing speed,balls cones,intermediate,Sprint from cone to finish first-time on service.,15
13,COND_004,Defensive Recovery Runs,conditioning_with_ball,30x20,6,12,"DEF,GK",defending pace,cones balls,advanced,Recover from central line into defending shape...,15
14,COND_005,1v1 Continuous Channel,conditioning_with_ball,15x20,4,8,ALL,pace dribbling,cones balls,intermediate,Continuous 1v1 in narrow lane creates repeated...,15
15,SSG_001,4v4 + 2 Neutrals,small_sided_games,30x25,10,12,ALL,possession passing,cones bibs balls,intermediate,Neutrals help maintain possession and find cen...,25
16,SSG_002,3-Goal Game,small_sided_games,30x30,8,12,ALL,decision_making finishing,cones goals balls,intermediate,Teams score on any of three small goals to pro...,25
17,SSG_003,End Zone Game,small_sided_games,35x25,8,12,ALL,passing movement,cones balls,beginner,Score by receiving in opponent’s end zone.,25
18,SSG_004,Conditioned Play: Two-Touch,small_sided_games,40x30,10,14,ALL,first_touch speed,cones bibs balls,intermediate,Forces quick decisions and body positioning.,25
19,SSG_005,Counterattack SSG,small_sided_games,36x28,8,12,"FWD,MID",transition finishing,cones balls,advanced,Immediate counterattacking moments after each ...,25
20,TAC_001,Creating Overloads,tactical,30x40,8,14,"MID,FWD",decision_making possession,cones bibs balls,intermediate,Work on numerical superiority and exploiting o...,20
21,TAC_002,Building From Back,tactical,40x50,8,14,"DEF,GK,MID",passing structure,cones bibs balls,advanced,"Shape, movement, and timing to exit pressure a...",20
22,TAC_003,Pressing Triggers,tactical,30x30,6,12,ALL,pressing awareness,cones bibs balls,advanced,Identify cues for team press and coordinate fi...,20
23,TAC_004,Transition Moments,tactical,30x40,6,12,ALL,decision_making pace,cones balls,intermediate,Switch instantly between defense and attack af...,20
24,TAC_005,Wide Channel Decision Play,tactical,20x40,6,12,"MID,FWD",passing crossing,cones balls,intermediate,Develop patterns down the flanks and final-thi...,20
25,TECH_001,Wall Pass Circuit,technical,20x30,6,12,"MID,FWD",passing first_touch,cones balls,intermediate,Players rotate through passing checkpoints foc...,25
26,TECH_002,First Touch Direction,technical,15x25,4,10,"MID,FWD,DEF",first_touch decision_making,cones balls,intermediate,Receive across body and play into target quickly.,25
27,TECH_003,1v1 Isolation,technical,12x18,2,6,"FWD,MID",dribbling finishing,cones balls,intermediate,Quick 1v1 reps with immediate resets.,25
28,TECH_004,Defensive Jockeying,technical,10x15,2,8,DEF,defending footwork,cones,intro,Players learn to angle attacker away and time ...,25
29,TECH_005,Finishing From Angles,technical,20x30,3,8,FWD,shooting first_touch,balls goals,advanced,Serve from wide areas and finish from staggere...,25

## Data Quality Checks

In [5]:
# Inspect data types and non-null counts
print("Dataset Info:")
drills_raw.info()

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   drill_id        30 non-null     object
 1   drill_name      30 non-null     object
 2   category        30 non-null     object
 3   field_size_yds  30 non-null     object
 4   players_min     30 non-null     int64
 5   players_max     30 non-null     int64
 6   positions       30 non-null     object
 7   attributes      30 non-null     object
 8   equipment       28 non-null     object
 9   difficulty      30 non-null     object
 10  description     30 non-null     object
dtypes: int64(2), object(9)
memory usage: 2.7+ KB

In [6]:
# Calculate missingness by column (sorted descending)
missingness = drills_raw.isna().mean().sort_values(ascending=False)

print("Missing Value Percentages (sorted by highest missingness):\n")
print(missingness[missingness > 0])  # Only show columns with missing values

if missingness[missingness > 0].empty:
    print("✓ No missing values detected in any column")

Missing Value Percentages (sorted by highest missingness):

equipment    0.066667
dtype: float64

In [7]:
# Check for list-like strings that will need parsing
# These often appear as: "['value1', 'value2', 'value3']"

print("Checking for list-like string patterns...\n")

for col in drills_raw.columns:
    # Check if column contains string data
    if drills_raw[col].dtype == 'object':
        # Sample first non-null value
        sample = drills_raw[col].dropna().iloc[0] if len(drills_raw[col].dropna()) > 0 else None
        
        if sample and isinstance(sample, str):
            # Check if it looks like a list string
            if sample.strip().startswith('[') and sample.strip().endswith(']'):
                print(f"⚠️  '{col}' contains list-like strings")
                print(f"    Example: {sample}")
                print()

Checking for list-like string patterns...

In [8]:
# Check numeric columns for min/max players, duration, etc.
numeric_cols = drills_raw.select_dtypes(include=['int64', 'float64']).columns

if len(numeric_cols) > 0:
    print("Numeric column summary:\n")
    print(drills_raw[numeric_cols].describe())
else:
    print("⚠️  No numeric columns detected - may need type conversion")

Numeric column summary:

       players_min  players_max
count    30.000000    30.000000
mean      6.000000    13.333333
std       2.051072     4.309839
min       2.000000     6.000000
25%       4.250000    10.500000
50%       6.000000    12.000000
75%       8.000000    15.500000
max      10.000000    20.000000